export const changeCssVariables = theme => {
    const root = document.querySelector(':root');

    root.style.setProperty(
        '--theme-default-body',
        `var(--theme-${theme}-body)`
    );
    root.style.setProperty(
        '--thema-default-bg-cl',
        `var(--thema-${theme}-bg-cl)`
    );
    root.style.setProperty(
        '--theme-default-header-bg',
        `var(--theme-${theme}-header-bg)`
    );
    root.style.setProperty(
        '--theme-default-select-bg',
        `var(--theme-${theme}-select-bg)`
    );
    root.style.setProperty(
        '--theme-default-select-border',
        `var(--theme-${theme}-select-border)`
    );
    root.style.setProperty(
        '--thema-default-option-hover-cl',
        `var(--thema-${theme}-option-hover-cl)`
    );
    root.style.setProperty(
        '--theme-default-sidebar-bg',
        `var(--theme-${theme}-sidebar-bg)`
    );
    root.style.setProperty(
        '--theme-default-sidebar-text',
        `var(--theme-${theme}-sidebar-text)`
    );
    root.style.setProperty(
        '--theme-default-indicator-color',
        `var(--theme-${theme}-indicator-color)`
    );
    root.style.setProperty(
        '--theme-default-line-color',
        `var(--theme-${theme}-line-color)`
    );
    root.style.setProperty(
        '--theme-default-logo-color',
        `var(--theme-${theme}-logo-color)`
    );
    root.style.setProperty(
        '--theme-default-logo-bg',
        `var(--theme-${theme}-logo-bg)`
    );
    root.style.setProperty(
        '--theme-default-link-bg',
        `var(--theme-${theme}-link-bg)`
    );
    root.style.setProperty(
        '--theme-default-link-text',
        `var(--theme-${theme}-link-text)`
    );
    root.style.setProperty(
        '--theme-default-createbutton-bg',
        `var(--theme-${theme}-createbutton-bg)`
    );
    root.style.setProperty(
        '--theme-default-createbutton-focusbg',
        `var(--theme-${theme}-createbutton-focusbg)`
    );
    root.style.setProperty(
        '--theme-default-controlicon-color',
        `var(--theme-${theme}-controlicon-color)`
    );
    root.style.setProperty(
        '--theme-default-createbutton-color',
        `var(--theme-${theme}-createbutton-color)`
    );
    root.style.setProperty(
        '--theme-default-needhelp-bg',
        `var(--theme-${theme}-needhelp-bg)`
    );
    root.style.setProperty(
        '--theme-default-logout-color',
        `var(--theme-${theme}-logout-color)`
    );
    root.style.setProperty(
        '--theme-default-logout-focuscolor',
        `var(--theme-${theme}-logout-focuscolor)`
    );
    root.style.setProperty(
        '--theme-default-modal-bg',
        `var(--theme-${theme}-modal-bg)`
    );
    root.style.setProperty(
        '--theme-default-modal-color',
        `var(--theme-${theme}-modal-color)`
    );
    root.style.setProperty(
        '--theme-default-input-bg',
        `var(--theme-${theme}-input-bg)`
    );
    root.style.setProperty(
        '--theme-default-button-bg',
        `var(--theme-${theme}-button-bg)`
    );
    root.style.setProperty(
        '--theme-default-button-text',
        `var(--theme-${theme}-button-text)`
    );
    root.style.setProperty(
        '--theme-default-bgicon-color',
        `var(--theme-${theme}-bgicon-color)`
    );
    root.style.setProperty(
        '--theme-default-bgicon-checkcolor',
        `var(--theme-${theme}-bgicon-checkcolor)`
    );
    root.style.setProperty(
        '--theme-default-plus-bg',
        `var(--theme-${theme}-plus-bg)`
    );
    root.style.setProperty(
        '--theme-default-plus-color',
        `var(--theme-${theme}-plus-color)`
    );
    root.style.setProperty(
        '--thema-default-filter-btn-cl',
        `var(--thema-${theme}-filter-btn-cl)`
    );
    root.style.setProperty(
        '--thema-default-filter-icon-cl',
        `var(--thema-${theme}-filter-icon-cl)`
    );
    root.style.setProperty(
        '--thema-default-filter-modal-overlay-cl',
        `var(--thema-${theme}-filter-modal-overlay-cl)`
    );
    root.style.setProperty(
        '--thema-default-filter-title-cl',
        `var(--thema-${theme}-filter-title-cl)`
    );
    root.style.setProperty(
        '--thema-default-filter-title-border-cl',
        `var(--thema-${theme}-filter-title-border-cl)`
    );
    root.style.setProperty(
        '--thema-default-filter-modal-border-cl',
        `var(--thema-${theme}-filter-modal-border-cl)`
    );
    root.style.setProperty(
        '--thema-default-filter-modal-bg-cl',
        `var(--thema-${theme}-filter-modal-bg-cl)`
    );
    root.style.setProperty(
        '--thema-default-filter-modal-close-icon-cl',
        `var(--thema-${theme}-filter-modal-close-icon-cl)`
    );
    root.style.setProperty(
        '--thema-default-filter-modal-show-cl',
        `var(--thema-${theme}-filter-modal-show-cl)`
    );
    root.style.setProperty(
        '--thema-default-filter-modal-radio-text-cl',
        `var(--thema-${theme}-filter-modal-radio-text-cl)`
    );
    root.style.setProperty(
        '--thema-default-filter-modal-radio-text-checked-cl',
        `var(--thema-${theme}-filter-modal-radio-text-checked-cl)`
    );
    root.style.setProperty(
        '--theme-default-card-bg',
        `var(--theme-${theme}-card-bg)`
    );
    root.style.setProperty(
        '--theme-default-card-descr',
        `var(--theme-${theme}-card-descr)`
    );
    root.style.setProperty(
        '--theme-default-card-board',
        `var(--theme-${theme}-card-board)`
    );
    root.style.setProperty(
        '--theme-default-scroll',
        `var(--theme-${theme}-scroll)`
    );
    root.style.setProperty(
        '--theme-default-scroll-bg',
        `var(--theme-${theme}-scroll-bg)`
    );
    root.style.setProperty(
        '--theme-default-edit-user',
        `var(--theme-${theme}-edit-user)`
    );
    root.style.setProperty(
        '--theme-default-column-plus',
        `var(--theme-${theme}-column-plus)`
    );
};
